### PR TITLE
adding a menu test

### PR DESCRIPTION
**Pull request by compojoom**
the code style is wrong (I have spaces instead of tabs, but I have no clue why this happens). All my other phpstorm projects use tabs, just this one refuses to use tabs???

Anyway :) other than that it should work.

### CODE REVIEW

**Comment by zero-24** [comment]
@compojoom I have just send a quick PR to fix the codestyle :smile:

**Comment by javigomez** [comment]
Thanks guys ^_^

**Comment by javigomez** [comment]
Regarding code style see: #66

Regarding the missing name in iframe I have created #67

@puneet0191  I'm merging this one, and afterwards we can consider to move MenuCest into JoomlaBrowser or into an Integration test.

**Comment by javigomez** [comment]
closing since was squashed and merged at c3893e725ad73d1adc21f24187f4451a1e81c24b

**Pull request closed without merging**
