### PR TITLE
[tests] Disable statistics for tests

### PR DESCRIPTION
**Pull request by javigomez**
Disables the stats message right after Joomla installs

capture 2016-02-01 at 11 50 16

### CODE REVIEW

**Comment by puneet0191** [comment]
@javigomez Not sure why this command is failing on travis 
https://travis-ci.org/joomla-extensions/weblinks/jobs/106183274#L1281

**Comment by javigomez** [comment]
is related to the changes in JoRobo at #184. Once we fix that one we can update the present pull and it will pass.

**Comment by javigomez** [comment]
@puneet0191 @810 @yvesh could any of you help me testing this one. You need do run the tests to see it in action.

**Comment by yvesh** [comment]
@javigomez tested, worked fine!

**Pull request merged**
