### PR TITLE
Test selenium v2.49.0

### PR DESCRIPTION
**Pull request by javigomez**
# Do not merge

This is just a test.

cc: @810

### CODE REVIEW

**Comment by 810** [comment]
@test ok windows 10 64bit

**Comment by javigomez** [comment]
I'm having issues to run it in local, and not sure what could be the issue based on TravisCI complain:

screen shot 2016-01-15 at 17 56 58

**Comment by 810** [comment]
I have the same error with 2.47.1 right now with windows, When i download newer versions, its working

**Comment by javigomez** [comment]
closing, since we have now 2.49.1. We will have to redo this pull with the new one.

**Pull request closed without merging**
