### PR TITLE
codestyle again

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issues at: https://travis-ci.org/joomla-extensions/weblinks/jobs/148560529

#### Summary of Changes

CS

#### Testing Instructions

please review the code as it just CS fixes. Please double check this file as it get mainitly rewritten to follow the codestyle ;) src/modules/mod_weblinks/tmpl/default.php

### CODE REVIEW

**Comment by puneet0191** [comment]
Looks good on Code Review, Thanks @zero-24 :+1:

**Comment by zero-24** [comment]
I hope we can enable the CS rules if that is in ;)

**Comment by yvesh** [comment]
Thank you @zero-24 :-)

**Comment by zero-24** [comment]
Can you re sync you pr again than? @yvesh

**Pull request merged**
