### PR TITLE
Added drone integration

### PR DESCRIPTION
**Pull request by yvesh**
Added .drone.yml and build script to weblinks. Tested with drone 0.4

drone

### CODE REVIEW

**Comment by yvesh** [comment]
@rdeutz 1and1 server needs

`docker pull yveshoppe/joomla-systemtests`

Somehow drone does not update images before running..

**Comment by rdeutz** [comment]
I have found that I have installed an old docker version, I followed the process but there was something cached so the package was pulled from an old source. I now have updated docker but hadn't have the time to look into it closer.

**Comment by yvesh** [comment]
Hmm Robert i fear that did not help.. Not sure what drone is doing and why the old image is still there..

Same commit worked fine here:

http://test01.compojoom.com/yvesh/weblinks/11

While it fails on 1and1 server.. Maybe we should start all over again? Or delay drone integration for some time until it gets more reliable..

**Comment by chrisdavenport** [comment]
What is the status of this PR? (Just trying to tidy up).

**Comment by yvesh** [comment]
@chrisdavenport closing my pull request, as we currently have no working root server for drone.io.

**Pull request closed without merging**
