### PR TITLE
Change latest copyright year with tag for automatic substitution

### PR DESCRIPTION
**Pull request by chrisdavenport**
#### Summary of Changes

Change latest copyright year with tag for automatic substitution by the build script.
#### Testing Instructions

Run build script and check that all files have the correct copyright date in them.

### CODE REVIEW

**Comment by yvesh** [comment]
@chrisdavenport That is not supported in the current JoRobo version. Currently the automatic substitution is only done for certain files, like script.php.

But i made an PR against JoRobo adding that functionality. See [here](https://github.com/joomla-projects/jorobo/pull/21).

**Comment by zero-24** [comment]
As the PR by @yvesh is merged can we move this forward?

**Comment by dgt41** [comment]
This might be stupid but we have `__DEPLOY_VERSION__` and then `##YEAR##`, so me thinking why different notation?

**Comment by yvesh** [comment]
@dgt41 different history.. ##YEAR##, ##VERSION## etc. is some years older then @andrepereiradasilva  __DEPLOY_VERSION__. 

You would need to ask him, why he choose that syntax ;-)

But it's a good idea to standardize these things too.

**Comment by mbabker** [comment]
We started using the deploy version placeholder on the Framework in
2013/2014 and it gets replaced by our Jenkins job that handles git tags.
So that's its history.

**Comment by andrepereiradasilva** [comment]
when created the bump.php version script (https://github.com/joomla/joomla-cms/blob/staging/build/bump.php) on the CMS i followed the same principle as the framework , ie, use `__DEPLOY_VERSION__`

Later added the automatic year change in copyright also in the cms on script build without the need for a varible (just preg_replace).
https://github.com/joomla/joomla-cms/blob/staging/build/bump.php#L307

**Comment by chrisdavenport** [comment]
Closing as this is not the right approach.

**Pull request closed without merging**
