### PR TITLE
Improved the Batch view of com_weblinks

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue https://github.com/joomla-extensions/weblinks/issues/367.

### Summary of Changes
I changed the batch view of com_weblinks analogously to the batch view of com_content.

### Testing Instructions
1. Create a few weblinks via com_weblinks (Components | Web Links).
2. Select all this weblinks and click the toolbar button batch
3. See that the view has a nice margin.
4. Please also check that the component is still working correctly. For example: Move weblinks to another category or change the tags.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 5889e025d4279d6ae3d2b49e0afa0dc509baf48e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/375">issues.joomla.org/tracker/weblinks/375</a>.</sub>

**Comment by yvesh** [comment]
@astridx can you check the issues? Thank you :-)

**Comment by astridx** [comment]
@franz-wohlkoenig  Thank you for testing so reliable.
I tried to adjust your error message. For me, the view is without error.

web links joomla cms test administration

My first idea:
Line 152 of the file JOOMLA/administrator/components/com_weblinks/views/weblinks/tmpl/default.php need the variable associations. This variable was introduced in this PR a few days ago:
https://github.com/joomla-extensions/weblinks/pull/349

Could it be, that this PR is not merged well in your testing installation? How did you update your system?

**Comment by franz-wohlkoenig** [comment]
I use pkg-weblinks-3.7.0-beta1.zip. I can download it once more an test again if you say so.

**Comment by franz-wohlkoenig** [comment]
I think so too but didn't find a actual Source.

**Comment by astridx** [comment]
@franz-wohlkoenig If you like you can try with the source I uploaded here a few minutes ago: https://github.com/joomla-extensions/weblinks/pull/377

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 5889e025d4279d6ae3d2b49e0afa0dc509baf48e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/375">issues.joomla.org/tracker/weblinks/375</a>.</sub>

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you very much for testing.

**Comment by franz-wohlkoenig** [comment]
thanks for your Work @astridx.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5889e025d4279d6ae3d2b49e0afa0dc509baf48e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/375">issues.joomla.org/tracker/weblinks/375</a>.</sub>

**Comment by astridx** [comment]
Thanks for the test @alikon 
It would be great if some could merge take. There are now three successful tests.

Can we create a new Tag?

**Comment by yvesh** [comment]
Thanks @astridx .. Merged it in the master branch now.. we need to bump version anyways and do another beta / rc to get all the improvements of the last months out.

**Pull request merged**
