### PR TITLE
Add Support for translating one item via Multilingual Associations

### PR DESCRIPTION
**Pull request by astridx**
### Testing Instructions
Create a weblink item and translate it via Multilingual Associations Component

### Expected result
Up to now we only support translation of categories. With this PR it is possible to translate also weblink items.

### CODE REVIEW

**Comment by astridx** [comment]
Some checks are not successful:
The first one: tests/acceptance/install/InstallWeblinksCest.php:installJoomla failed

It fails because of a spellchange in the danish Languagefiles. This change is fixed in Joomla Browser, but we do not use the current Version of JoomlaBrowser ...

**Comment by infograf768** [comment]
we never added associations for individual weblinks as they make no sense.
this should be closed.

**Comment by zero-24** [comment]
> we never added associations for individual weblinks as they make no sense.
this should be closed.

@infograf768 as with 3.7.1 release of weblinks we will have a single weblink view wich would make sense to be translated IMO

**Comment by infograf768** [comment]
i don't think you understand : it just does NOT make sense. Cliking on a web link displays in another page, not in joomla. this means tha the switcher can never be used. you just can't associate them. period. you can associate their categories and display them in function of the language but not associate them.

**Comment by zero-24** [comment]
Please check: https://github.com/joomla-extensions/weblinks/pull/336 @infograf768 this is a new feature we are trying to release with a new release of weblinks.

**Comment by infograf768** [comment]
hmm... are you sure all this is really useful?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a66418fa0a812c54f1bfc173727267d3ad67dc22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/346">issues.joomla.org/tracker/weblinks/346</a>.</sub>

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you very much for testing. The missing string is in there now.

@infograf768  You are right. The single view is not really neccessary. But I think weblinks is a component where others (and I) have the opportunity to learn creating componentens. Thats why I think the single view is OK.

**Comment by infograf768** [comment]
@astridx
As I am not sure both your patches take care of all aspects of associations, I have done here a full implementation of associations for weblinks, which also let's set the assoc when editing a weblink (not through multilingual assocations) as we do for other core components.
It is based on the existing release version of weblinks, but I am sure it will be easy for you to see the .diff with this master one.

Example (without the new ini strings)
screen shot 2017-05-14 at 08 57 50
screen shot 2017-05-14 at 08 57 34

screen shot 2017-05-14 at 09 04 49

I let you look and implement it if it does not yet exists in your patches:
Admin:
[com_weblinks.zip](https://github.com/joomla-extensions/weblinks/files/999159/com_weblinks.zip)
Site:
[com_weblinks.zip](https://github.com/joomla-extensions/weblinks/files/999160/com_weblinks.zip)

**Comment by infograf768** [comment]
@astridx @zero-24 
I am now preparing a full .diff which will contain this + #336 + my changes.

**Comment by infograf768** [comment]
Here it is

[weblinks.patch.zip](https://github.com/joomla-extensions/weblinks/files/999547/weblinks.patch.zip)

**Comment by astridx** [comment]
@infograf768 
Thank you very much. I  (and surely @zero-24) will have a closer look on it next week.

**Comment by infograf768** [comment]
Note: there will be some corrections to do in my patch concerning the lang strings

**Comment by astridx** [comment]
Close because of https://github.com/joomla-extensions/weblinks/pull/349

**Pull request closed without merging**
