### PR TITLE
Move lang files for search plugin

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #290

### Summary of Changes

Move language files for the search plugin into the plugin distribution file. This makes all the plugins consistent in not putting language files into administrator/language.

### Testing Instructions

- Install 3.7.0b2
- apply this patch
- confirm the language files in the plugins folder

### Expected result

the language files in the plugins folder

### Actual result

the language files are not in the plugins folder

### Documentation Changes Required

None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
> Install 3.7.0b2

"3.7.0b2" is the latest staging (=weblinks.master.zip)?

**Comment by zero-24** [comment]
3.7.0b2 means the CMS not the weblinks ;)

**Comment by franz-wohlkoenig** [comment]
i have 3.7.0-rc1 (neweset nightly build) installed. Can i test on this?

**Comment by infograf768** [comment]
I have no problem with this if we keep putting the lang files in the admin part in the CMS.
If any change has been done for weblinks where lang files are not put into the admin or site main languages folders, please revert!

**Comment by zero-24** [comment]
Yes @franz-wohlkoenig

Yes @infograf768 that is the plan.

**Comment by infograf768** [comment]
tks for reply.

**Comment by zero-24** [comment]
This is just to clean up the repo here ;)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 64d246fd2f15c7a0fbe0a693b8f85db33dea099e<br /><br />After PR are Lang.-Files in Folder:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/334">issues.joomla.org/tracker/weblinks/334</a>.</sub>

**Comment by yvesh** [comment]
Thank you @zero-24

**Comment by zero-24** [comment]
Thanks @yvesh

**Pull request merged**
