### PR TITLE
Implements searchtools, filters, dropdown actions and counting

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR, as done in all other core list views, implements swearchtools in weblinks.

Also:
- Some minor code improvements
- Add max level filter (as done for other core views)
- Add dropdown actions (as done for other core views)
- Integrates the other two PR: (as done for other core views)
 - Category counting https://github.com/joomla-extensions/weblinks/pull/207
 - Category text https://github.com/joomla-extensions/weblinks/pull/177

This PR as a whole, will put com_weblinks in line with the other core views.

###### Web Links view

Before PR

image

After PR

image

###### Web Links categories view

Before PR

image

After PR

image

#### How to test

1. Install the custom weblinks from URL https://github.com/andrepereiradasilva/update.joomla.org/raw/master/pkg-weblinks-3.5.0.zip
2. Create some weblinks
3. Test searchtools (seacrh, filters, orderings, pagination)
4. Test dropdown actions
5. Go to Categories and test the counting and their links

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@brianteeman @MATsxm want to test this one too so weblinks can be consistent with core?

This does not work with Patchtester, but as you can see in the test instructions i made a custom weblinks package with the changes.

Also, i think you have to use the https://issues.joomla.org/tracker/weblinks to mark the test results.

**Comment by andrepereiradasilva** [comment]
@yvesh reggarding the tests failed, i think this will change some of the browser tests where the filters are selected.

**Comment by javigomez** [comment]
@yvesh @andrepereiradasilva just merged #205

**Comment by andrepereiradasilva** [comment]
how do we rerun travis?

**Comment by andrepereiradasilva** [comment]
ok running again

**Comment by andrepereiradasilva** [comment]
ok, no wi only get the filter failure. https://travis-ci.org/joomla-extensions/weblinks/jobs/127293973#L1992

image

But i guess that was supposed to happen because this PR changes the filters.

**Comment by andrepereiradasilva** [comment]
i think somewhere is missing a $I->clickSearchToolsButton :)

**Comment by yvesh** [comment]
Hey @andrepereiradasilva, i fear it's a bit more difficult. Currently working on a fix for you.

But i think there is a bug in your PR: There is no delete button showing up, when you switch to trashed view?

screenshot 2016-05-02 20 46 51

So you can't delete a weblink permanently? 

Thank you for your work! 👍

**Comment by andrepereiradasilva** [comment]
> i fear it's a bit more difficult.

Never is so simple.

> But i think there is a bug in your PR: There is no delete button showing up, when you switch to trashed view?

nice spoted! i will check that!

**Comment by yvesh** [comment]
@andrepereiradasilva The following should fix it, if you want i can also make a pull request to your repository.

```php
$I->click('Search Tools');
$I->wait(2);
$I->selectOptionInChosenById('filter_published', 'Trashed');
```

Replace line 102 in tests/acceptance/administrator/AdministratorWeblinksCest.php with that.

https://github.com/joomla-extensions/weblinks/blob/master/tests/acceptance/administrator/AdministratorWeblinksCest.php#L102

You also need to update your fork repositor, else you run into new troubles! :-)

> This branch is 6 commits ahead, 5 commits behind joomla-extensions:master

**Comment by andrepereiradasilva** [comment]
will do @yvesh. thanks for the help!

**Comment by andrepereiradasilva** [comment]
Test passed. All should be fine now. thanks again.

**Comment by yvesh** [comment]
Tested with MySQL and staging. Works as expected, no issues found.

Sytemtests are also working:

screenshot 2016-05-12 16 04 45

PR has some code style issues @andrepereiradasilva in countItems(..)

**Comment by andrepereiradasilva** [comment]
thanks. ok now?

**Comment by andrepereiradasilva** [comment]
tests failed, but i think is not related to my PR

**Comment by yvesh** [comment]
@andrepereiradasilva Yes, the travis failure has nothing todo with your PR. It's related to a change in Joomla staging in the installer. 

There is already a PR open for that issue in joomla-browser. Should be fixed soon :-) 

Thank you for your work! :-)

**Comment by pritalpatel** [comment]
Thanks @andrepereiradasilva 

Tested manually as well as automatically. All seems working fine.

weblink-success2
weblink-success

**Comment by andrepereiradasilva** [comment]
will anyone merge this before it gets conflicts?

**Comment by chrisdavenport** [comment]
Finally got around to reviewing this one.  Sorry for the delay.

Looks good.  Thanks @andrepereiradasilva Thanks everyone for testing and feedback.

**Pull request merged**
