### PR TITLE
Move weblinks stats to weblinks repo

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #288 (redo because of merge conflicts)

### Summary of Changes

Move web links statistics shown on the admin control panel from Joomla core to a system plugin in the web links package.

### Testing Instructions

- install 3.7.0 (as this is a new plugin event)
- Create at least one published web link.
- apply this pr
- discover the new plugin
- install ist
- Enable the system plugin.
- You should now have an entry about the weblinks count.

### Expected result

You should now have an entry about the weblinks count.

### Actual result

You don't see any count in the CMS it selfe (in 3.7.0b)

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
> install 3.7.0 (as this is a new plugin event)

means installing weblinks-master.zip?

**Comment by zero-24** [comment]
Last cms version ;)

**Comment by franz-wohlkoenig** [comment]
installed weblinks-master.zip on 3.7.0-rc1:
bildschirmfoto 2017-03-24 um 18 14 52

**Comment by zero-24** [comment]
You can not install weblinks master you need to use the last published version of weblinks ;)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on efc3e398d6063cec0bd4f74842080a6fd2939811<br /><br />After PR in Module "Statistics" Weblink + Count is shown:

After installing weblink-pkg. Lang.String is missed:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/333">issues.joomla.org/tracker/weblinks/333</a>.</sub>

**Comment by zero-24** [comment]
I have just fixed a tab to spaces error. 

@franz-wohlkoenig this is expected behavior as the XML file is generated on the time @yvesh release a new version.

**Comment by astridx** [comment]
I tested this patch successfully

    I created a web link.
    I created a menu item and clicked the weblink one time and I saw one hit.
    I created an admin module of the type statistic. I see no entry for this in the module because the core patch is merged.
    After that I copied the system plugin from this patch into the system plugin folder of my installation, discovered it and activated it.
    After that I saw an entry for my weblink in the statistic module

**Comment by zero-24** [comment]
Thanks @astridx

**Pull request merged**
