### PR TITLE
Create a menu item: Displays a list of Web Links for a category

### PR DESCRIPTION
**Pull request by kshitijSharma2014**

### CODE REVIEW

**Comment by kshitijSharma2014** [comment]
@puneet0191  @javigomez  @Kubik-Rubik @zanardigit Please review it

**Comment by Kubik-Rubik** [comment]
@kshitijSharma2014 Please write a short description and a howto (even if it is just to check whether the tests are running properly). Thank you!

**Comment by kshitijSharma2014** [comment]
This PR solves the second last issue mentioned here: https://github.com/joomla-extensions/weblinks/issues/47

Through this test
1. create a weblink category
2. create a weblink of that category
3. create menu item of type list of Web Links for a category
4. confirm the creation of the weblink in the front-end.

**Comment by therunnergit** [comment]
@Test works fine.

**Comment by Kubik-Rubik** [comment]
Works as described. Thank you @kshitijSharma2014! Merged.

**Comment by puneet0191** [comment]
@Kubik-Rubik I am reverting the PR, removes some code which was needed. @kshitijSharma2014 will redo a fresh PR for adding this.

**Pull request merged**
