### PR TITLE
Update default jorobo.dist.ini build version to 3.5.0

### PR DESCRIPTION
**Pull request by yvesh**

### CODE REVIEW

**Comment by yvesh** [comment]
The pull requests fails because of PHP 5.5 version. The latest codeception version and it's dependencies require PHP 5.6. 

screenshot 2016-05-01 21 10 00

We need to find a solution for that. Either separate cpmmand line php version and apache one or dropping PHP 5.5 support and go for PHP 7 instead. (So we stick to two versions).

**Comment by mbabker** [comment]
No the issue is you've committed a lock file with PHP 5.6+ dependencies.  Codeception's dependencies are PHP 5.4+ but it supports PHPUnit 4.8 and 5.x (5.x has PHP 5.6 as a minimum dependency).  The composer.json file will most likely need a `config.platform.php` key specifying a specific PHP version to use for checking dependencies to ensure this doesn't happen going forward.

**Comment by yvesh** [comment]
@mbabker Sure adding php 5.5 as platform to the composer.json would fix it. But is this also the way to go? Should we stick to PHP 5.5? :-)

**Comment by mbabker** [comment]
Using `config.platform.php` is the way to go if you're committing a lock file on a distributed project.  For example the CMS has a 5.3.10 minimum but I work locally on 7.0 so to ensure the dependencies for the CMS aren't accidentally raised either you'd have to use rather strict version constraints in your require/require-dev sections, always run updates from a machine having your minimum requirements, or set the `config.platform.php` key which tells Composer to ignore your environment's PHP version and always use the one you specify in the key.

**Comment by yvesh** [comment]
Okay, thank you for your input on that @mbabker 👍

**Pull request merged**
