### PR TITLE
[4.0] Move de-DE to this repo

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomlagerman/joomla/pull/805

### Summary of Changes

As of Joomla 4.0 this file is not longer part of the core distribution so here the suggestion to keep the translation in this repo.

### Testing Instructions

Install weblinks in 4.0 + de-DE installed

### Expected result

GUI translated

### Actual result

GUI not translated

### Documentation Changes Required

none

### CODE REVIEW

**Comment by zero-24** [comment]
@HLeithner @wilsonge any opinions here? else we can close here and just trash the translation.

**Comment by HLeithner** [comment]
We should have own language packages for these translation or shouldn't they be part of the german language pack?

**Comment by infograf768** [comment]
Thoughts

1. Crowdin is not taking care of these when people use it to create core lang packs.
2. Looks like the module and plugins lang files are missing in this repo (if i do not mistake)
3. We have decided to include all fr-FR webkinks lang files in our general lang pack, but I have no idea about other TTs also doing so.
4. There is no process to install another language weblinks lang files from this repo in function of the site installed languages.
5. Starting to include them in the core of this repo could be considered as a solution, except if we advertise this and get many languages doing such. I doubt about it, but it could happen theoritically.

Conclusion: the separation of this component from core was done in amateur way... Was it really necessary? Should it had been kept still as a supported extension while no good solution was provided concerning languages ?

Sorry if this is considered as a rant.

**Comment by HLeithner** [comment]
So we should find a solution for this process, because it's possible that more components will be decoupled. May understanding was that the weblink decoupling was a test to learn how to it right... It seams there are improvements necessary to achieve this.

**Comment by zero-24** [comment]
Any update on this topic? Is there anything against merging this into the repo and maybe remove it when there is a better solution?

**Comment by infograf768** [comment]
Nothing new as far as I know.

**Comment by wilsonge** [comment]
Makes sense to me to setup up full crowdin integration here

**Comment by HLeithner** [comment]
based on downloads.joomla.org and the integration of j4 languages.

**Comment by zero-24** [comment]
> Makes sense to me to setup up full crowdin integration here

This would result into the current behavior that the TT's have to ship that with thier translation packages right? Why not ship it with the component like all other extensions handle translation, for sure an crowdin implementation could make sense but i would suggest to keep it out of the core translation packages and just ship it with the component.

**Comment by infograf768** [comment]
Shipping ALL languages with the package (comp, mod, plugins) would be very heavy and independent on the installed languages.

**Comment by zero-24** [comment]
Any progress made on that topic here or should that PR here just be closed? @infograf768 @HLeithner @wilsonge ?

**Comment by zero-24** [comment]
Thanks :)

**Pull request merged**
