### PR TITLE
Update selenium version to 2.52.0

### PR DESCRIPTION
**Pull request by pritalpatel**
Updated selenium version to v2.52.0

### CODE REVIEW

**Comment by puneet0191** [comment]
Thanks @pritalpatel this is a good start :+1:

**Comment by yvesh** [comment]
@pritalpatel we have a open pull request from @javigomez #188, which needs to be merged first.

**Comment by pritalpatel** [comment]
ohh! Thanks @puneet0191  @yvesh for the info. I didn't notice that. I will close this PR.

**Comment by yvesh** [comment]
You could have kept this PR open - for testing 2.52 after #188 (which updates to 2.51 and is already tested) ;)

**Comment by pritalpatel** [comment]
ok. let me reopen it.

**Comment by pritalpatel** [comment]
I am also trying to test @javigomez PR. @gunjanpatel is helping me for how to test etc... :)

**Comment by yvesh** [comment]
Great, getting everything set up and running is the most difficult part ;) Writing tests is easy afterwards..

**Comment by pritalpatel** [comment]
Indeed. It is hard to setup.

**Comment by javigomez** [comment]
@pritalpatel  please accept my changes against your current pull at: https://github.com/pritalpatel/weblinks/pull/1

**Comment by javigomez** [comment]
Nice! TravisCI passed. Thanks @pritalpatel ^_^

**Comment by pritalpatel** [comment]
Thanks@javier

**Pull request merged**
