### PR TITLE
Adds idividual test run command

### PR DESCRIPTION
**Pull request by javigomez**
This pull adds two new commands to Robo

screen shot 2015-06-09 at 13 53 36

@hikashop-nicolas will you help me to ensure these commands work in Windows based systems too?

Thanks :smile:

### CODE REVIEW

**Comment by puneet0191** [comment]
@javigomez  Just verified it works like a charm! :+1: 
image
Executing run:test command 
image

**Comment by javigomez** [comment]
awesome, please merge.

**Comment by rdeutz** [comment]
@javigomez could you have a look travis failed after the merge, all was on green before

**Comment by Bakual** [comment]
I think that is related to the manager name changes from Brian. Since Selenium expects specific names it's now broken and needs to be adjusted.

**Comment by javigomez** [comment]
yup. Fixing.

**Pull request merged**
