### PR TITLE
Fix Apache running on PHP 5.3 instead of 5.5

### PR DESCRIPTION
**Pull request by javigomez**
This pull is the clean version of #113

It fixes a issue in the travis build that was running PHP 5.3 instead of 5.5 as specified in the Travis.yml file.

I'm also removing the tests on PHP 7. It will be added once this issue is fixed https://github.com/joomla-extensions/weblinks/issues/114

### CODE REVIEW

**Comment by zero-24** [comment]
@javigomez you have merge conflicts here :smile:

**Comment by javigomez** [comment]
oops. Thanks @zero-24

**Comment by javigomez** [comment]
conflicts solved and one issue created for the future https://github.com/joomla-extensions/weblinks/issues/120

**Comment by Kubik-Rubik** [comment]
Thank you @javigomez! Merged.

**Pull request merged**
