### PR TITLE
[tests] Update Selenium and JoomlaBrowser

### PR DESCRIPTION
**Pull request by javigomez**
This pull:

- [x] Updates selenium to latest version 2.51.0.
- [x] To latests JoomlaBrowser 3.4.8v2 including this new function https://github.com/joomla-projects/joomla-browser/pull/100
- [x] Forces Travis to use latest Firefox v44
- [x] Fixes errors raised with the new selenium and Firefox

I have tested in my local MacOS, let's see if Travis Ubuntu do not complain.

@810 I would appreciate if you could run it on Windows. Thanks

### CODE REVIEW

**Comment by yvesh** [comment]
@javigomez Great work!

Tested, works fine with latest Firefox (44.0.1) on Linux!

**Comment by 810** [comment]
+1

**Comment by pritalpatel** [comment]
I am testing this PR. I am having issue with `WaitForSeleniumStandaloneServer` task. As shown below

waitforseleniumstandaloneserver

I think it's not related to this PR, but as per Gunjan's suggestion I commented `$this->runSelenium();` function for temporary and then it works smooth, whole flow is working fine afterwords.

**Comment by pritalpatel** [comment]
Forget to mention that I am using Ubuntu 14.04.

**Comment by puneet0191** [comment]
@pritalpatel thanks :) I can see you have not enabled or installed php-curl extension on your Ubuntu machine. I would suggest you to enable the curl extension and then try again.

**Comment by yvesh** [comment]
@puneet0191 it's not the curl extension, it's the curl programe.
@pritalpatel install curl -> apt-get install curl

**Comment by puneet0191** [comment]
@yvesh thanks :) you rock! :guitar:

**Comment by gunjanpatel** [comment]
Thanks @puneet0191 php5-curl is by default enabled in my machine. You are right @yvesh I will help @pritalpatel to install Binary curl (We are using same machine :-D ) :+1:

**Comment by javigomez** [comment]
Ok, given the 3 tests I'm merging. Actually there is a new release of Selenium, so I'll send the new update in a new pull.

**Pull request merged**
