### PR TITLE
Update AdministratorCategoriesCest.php

### PR DESCRIPTION
**Pull request by kshitijSharma2014**
Added tests

### CODE REVIEW

**Comment by kshitijSharma2014** [comment]
@puneet0191  @javigomez please review it.
thanks

**Comment by chrisdavenport** [comment]
What is the status of this PR? (Just trying to tidy up).

**Comment by puneet0191** [comment]
@kshitijSharma2014  You might have to update these tests.

**Comment by yvesh** [comment]
@kshitijSharma2014 Can you please give an update here? :-) Else we close for now, but would be nice if you can update them to work with latest staging and weblinks. Thank you!

**Comment by yvesh** [comment]
Closing for now, feel free to open it again after you updated them :-)

**Pull request closed without merging**
