### PR TITLE
Create associations.php helper to let weblinks be used into com_associations

### PR DESCRIPTION
**Pull request by infograf768**
This should be merged after the new com_associations gets in core
https://github.com/joomla/joomla-cms/pull/13537

### CODE REVIEW

**Comment by infograf768** [comment]
No idea why Travis fails...

**Comment by yvesh** [comment]
@infograf768 There is currently an issue with Travis, just ignore. :-) 

P.P.S.: __DEPLOY_VERSION__ is currently not support by the build script of weblinks (have it on the TODO)

**Comment by infograf768** [comment]
@yvesh 
when you will merge, please just modify the `__DEPLOY_VERSION__` to fit weblinks

**Comment by infograf768** [comment]
@yvesh Please merge this (after modifying the version) as com_associations is now in core

**Comment by yvesh** [comment]
@infograf768 Chris is working on a release of Weblinks for Joomla! 3.6 in the next weeks. So we can't merge that before (or we make a new weblinks 3.7 branch)

**Comment by infograf768** [comment]
You decide folks, but be aware that this new helper has no impact whatsoever on weblinks by itself i.e. if indeed it will only be useful in J 3.7, it could go in next weblinks release and be immediately available when 3.7 is released.

**Comment by franz-wohlkoenig** [comment]
In "Multilingual Associations" no Weblink but Categories shown:

bildschirmfoto 2017-02-14 um 21 46 30

**Comment by infograf768** [comment]
@franz-wohlkoenig
Weblinks only implement associations for categories. That is fine.

**Comment by zero-24** [comment]
Thanks @infograf768

**Pull request merged**
