### PR TITLE
Updating composer dependencies and fixing tests in weblinks

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

Updates composer dependencies and fixes RoboFile env

### Testing Instructions

Check if travis still works and tests run locally (see README.md)

### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
Travis is failing :smile: 

```
PHP Fatal error:  Call to a member function newBuilder() on a non-object in /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Common/BuilderAwareTrait.php on line 44
PHP Stack trace:
PHP   1. {main}() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/robo:0
PHP   2. Robo\Runner->execute() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/robo:20
PHP   3. Robo\Runner->run() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Runner.php:111
PHP   4. Symfony\Component\Console\Application->run() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Runner.php:157
PHP   5. Symfony\Component\Console\Application->doRun() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Application.php:120
PHP   6. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Application.php:189
PHP   7. Symfony\Component\Console\Command\Command->run() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Application.php:848
PHP   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Command/Command.php:262
PHP   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:390
PHP  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:108
PHP  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:129
PHP  12. call_user_func_array:{/home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:180}() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:180
PHP  13. RoboFile->build() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:180
PHP  14. Joomla\Jorobo\Tasks\Build->run() /home/travis/build/joomla-extensions/weblinks/RoboFile.php:548
PHP  15. Joomla\Jorobo\Tasks\Build->prepareDistDirectory() /home/travis/build/joomla-extensions/weblinks/vendor/joomla-projects/jorobo/src/Tasks/Build.php:68
PHP  16. Robo\Tasks->_mkdir() /home/travis/build/joomla-extensions/weblinks/vendor/joomla-projects/jorobo/src/Tasks/Build.php:120
PHP  17. Robo\Tasks->taskFilesystemStack() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Task/Filesystem/loadShortcuts.php:68
PHP  18. Robo\Tasks->task() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Task/Filesystem/loadTasks.php:85
PHP  19. Robo\Tasks->collectionBuilder() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/TaskAccessor.php:44
Fatal error: Call to a member function newBuilder() on a non-object in /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Common/BuilderAwareTrait.php on line 44
Call Stack:
    0.0001     241008   1. {main}() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/robo:0
    0.0085    1432104   2. Robo\Runner->execute() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/robo:20
    0.0144    2188176   3. Robo\Runner->run() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Runner.php:111
    0.2898    7038144   4. Symfony\Component\Console\Application->run() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Runner.php:157
    0.2935    7040664   5. Symfony\Component\Console\Application->doRun() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Application.php:120
    0.2936    7041704   6. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Application.php:189
    0.2949    7072104   7. Symfony\Component\Console\Command\Command->run() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Application.php:848
    0.2953    7074096   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /home/travis/build/joomla-extensions/weblinks/vendor/symfony/console/Command/Command.php:262
    0.2956    7098448   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:390
    0.2956    7098672  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:108
    0.2957    7099048  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:129
    0.2957    7101304  12. call_user_func_array:{/home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:180}() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:180
    0.2957    7101720  13. RoboFile->build() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/annotated-command/src/CommandProcessor.php:180
    0.2970    7300352  14. Joomla\Jorobo\Tasks\Build->run() /home/travis/build/joomla-extensions/weblinks/RoboFile.php:548
    0.2971    7301176  15. Joomla\Jorobo\Tasks\Build->prepareDistDirectory() /home/travis/build/joomla-extensions/weblinks/vendor/joomla-projects/jorobo/src/Tasks/Build.php:68
    0.2971    7301288  16. Robo\Tasks->_mkdir() /home/travis/build/joomla-extensions/weblinks/vendor/joomla-projects/jorobo/src/Tasks/Build.php:120
    0.2971    7301320  17. Robo\Tasks->taskFilesystemStack() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Task/Filesystem/loadShortcuts.php:68
    0.2971    7301488  18. Robo\Tasks->task() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Task/Filesystem/loadTasks.php:85
    0.2971    7301856  19. Robo\Tasks->collectionBuilder() /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/TaskAccessor.php:44
ERROR: Call to a member function newBuilder() on a non-object 
in /home/travis/build/joomla-extensions/weblinks/vendor/consolidation/robo/src/Common/BuilderAwareTrait.php:44
```

looks like a upstream issue?

**Comment by yvesh** [comment]
Looks likes an issue with the newest robo.li, need to debug that :)

@jatitoam didn't you had that already?

**Comment by jatitoam** [comment]
Yeah it needs adjustments which I'm working on but using the newest feature branches in Robo and the other repos.
I'm working on it.

**Comment by 810** [comment]
This one can be closed, all changes are already merged.

@jatitoam Did you fixed the issues?

**Pull request closed without merging**
