### PR TITLE
Don't strip Time info

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
There is no need to strip the time info from the `created` column. This information might be useful in case of timezone differences or whatever. Let the formatting be done at the template level.

Pull Request for Issue # .

### Summary of Changes
Removed this from the database query:
`DATE_FORMAT(a.created, "%Y-%m-%d") AS created`

Because why wouldn't you want the full datetime info?

### Testing Instructions

Create a weblinks module. It should display the same way with or without the patch.

### Expected result

No direct change expected. 

### Actual result

No direct change actually.

### Documentation Changes Required

No

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
I'm sure that this failure has nothing to do with me. Isn't there a problem with Travis?

**Comment by okonomiyaki3000** [comment]
Hello? Somebody want to have a look at this? This build failure has nothing to do with this PR. Please fix your Travis and run it again.

**Comment by okonomiyaki3000** [comment]
Hey! Fix your travis and merge this patch, ok?

**Comment by okonomiyaki3000** [comment]
:pineapple:

**Comment by okonomiyaki3000** [comment]
Hello? Anybody home in here? Your Travis is drunk and this a solid improvement. Let's get it merged.

**Comment by mbabker** [comment]
Is this the appropriate time to open the infamous "is this repo abandoned" issue?

**Comment by yvesh** [comment]
Needs at least one test, than I merge it. Not sure if there was a reason to add the strip before hand.

**Comment by alikon** [comment]
despite Travis 
it works as expected

**Comment by okonomiyaki3000** [comment]
@yvesh It looks like @alikon has tested it but is there some official way to report a successful test?

**Comment by okonomiyaki3000** [comment]
Just take this damn patch. It's obviously nonsense to strip the time information here. Why would you do that?

**Comment by alikon** [comment]
i'm afraid this is abondonware

**Comment by zero-24** [comment]
@wilsonge and @HLeithner should have the propper access to merge things here :)

**Comment by joomdonation** [comment]
Thanks. Merging this because the change here is valid and we did the same change for the version for Joomla 4 sometime ago. However, as Joomla 3 is now in maintenance mode, I guess we won't release new version for Joomla 3 unless there are requests from other users.

**Pull request merged**
