### PR TITLE
Adding Alert when deleting weblinks.

### PR DESCRIPTION
**Pull request by infograf768**
Similar to https://github.com/joomla/joomla-cms/pull/8995 implemented in core.

### CODE REVIEW

**Comment by javigomez** [comment]
Thanks @infograf768  we will have to update the tests with the new Alert.

I'll mention it in the Automated Testing Working group chat.

**Comment by javigomez** [comment]
Pull sent at https://github.com/infograf768/weblinks/pull/1

**Comment by javigomez** [comment]
Please @infograf768 merge now https://github.com/infograf768/weblinks/pull/2 it should fix the new error

cc: @yvesh

**Comment by javigomez** [comment]
New update sent at https://github.com/infograf768/weblinks/pull/3

cc: @yvesh

**Comment by javigomez** [comment]
Tested. Working. 

Can I get a second tester? @yvesh @puneet0191 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/184">issues.joomla.org/weblinks/184</a>.</sub>

**Comment by yvesh** [comment]
@javigomez Test fails for me on Linux with selenium-server-standalone v2.49.1

But not sure if this is related..

1) Failed to test trashing a category in /administrator/ in AdministratorCategoriesCest::administratorTrashCategory (tests/acceptance/administrator/AdministratorCategoriesCest.php)

Facebook\WebDriver\Exception\UnknownServerException] Element is not clickable at point (783.0999755859375, 321.08331298828125). Other element would receive the click: <th class="nowrap center" width="1%"></th>
Command duration or timeout: 63 milliseconds
Build info: version: '2.49.1', revision: '7203e46', time: '2016-01-21 17:35:35'
System info: host: 'geeketeer', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.3.3-3-ARCH', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=44.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e660c1b3-94ee-43df-9ade-84504b2ec934

**Comment by javigomez** [comment]
Try with the version tagged in composer 2.47.1 https://github.com/joomla-extensions/weblinks/blob/master/composer.json#L13

Beyond 2.48 this issue raises in Mac and Linux (not in Windows, @810 already informed that is working good). I think is related to Chosen selector. We probably would have to study it and update JoomlaBrowser finding an alternative way to interact with that <select>.

**Comment by yvesh** [comment]
2.47.1 is not working for me at all for me. Probably because of the new firefox.

@javigomez  Which FF version are you using?

**Comment by 810** [comment]
for me this also failed.

2.47.1 & 2.49.1 FF 44.0 Windows 10 64bit build 14251

**Comment by 810** [comment]
Ok it was a java cache issue,
Now it worked half, building package isn't working correct on windows, i see only xml in the package, also symlink isn't working to the tests/joomla-cms3 dir

**Comment by yvesh** [comment]
@810 can you open a issue at jorobo package with the error output of the **build** process? You can call the build process standalone by just executing `robo build` via cmd. Thought we fixed all windows related issues..

**Comment by javigomez** [comment]
I'm using firefox `42.0`. Newer versions are failing to me.

**Comment by puneet0191** [comment]
@yvesh Use Selenium 2.48.2 With Latest version of Firefox on Linux, It is love and Magic at the same time :stuck_out_tongue:

**Comment by javigomez** [comment]
Maybe we can try to use keyboard instead to navigate throught that <select>: http://stackoverflow.com/questions/25929195/webdriver-element-is-not-clickable-chrome

**Comment by yvesh** [comment]
@puneet0191 Hmm having the same issue (Element not visible) with 2.48.2 as on 2.49.1. 

[Facebook\WebDriver\Exception\ElementNotVisibleException] Element is not currently visible and so may not be interacted with
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'

Is AdministratorCategoriesCest::administratorTrashCategory working for you?

**Comment by yvesh** [comment]
@javigomez Okay downgraded my Firefox version and with 2.47.1 everything worked.. Let's get this PR finally merged.

@infograf768 Tested, everything worked. 

Thank you :+1:

**Comment by javigomez** [comment]
I'm merging this one. And I'll be investigating how to solve the issue in 2.49.1 in a new pull.

Thanks all.

**Pull request merged**
