### PR TITLE
Update en-GB.com_weblinks.ini

### PR DESCRIPTION
**Pull request by remotehelp**
Lang variable COM_WEBLINKS_NUM_ITEMS missing for title NUM ITEMS in category list (pkg_weblinks_3.4.1.zip)

### CODE REVIEW

**Comment by zero-24** [comment]
Can you alpha order the new string?

**Comment by remotehelp** [comment]
zero-24 "Can you alpha order the new string?", - what do you mean?

**Comment by infograf768** [comment]
That means placing the new string in alphabetical order i.e. just after 
`COM_WEBLINKS_NUM="# of links:"`

**Comment by remotehelp** [comment]
done

**Comment by zero-24** [comment]
Works good here. RTC for 3.4.2 Thanks.

**Comment by therunnergit** [comment]
@Test reviewed, looks good to me

**Comment by Kubik-Rubik** [comment]
Thank you @remotehelp and testers! Merged.

**Pull request merged**
