### PR TITLE
Adding test to check if category got archived

### PR DESCRIPTION
**Pull request by kshitijSharma2014**

### CODE REVIEW

**Comment by therunnergit** [comment]
@Test works fine

**Comment by puneet0191** [comment]
@kshitijSharma2014 This can wait for https://github.com/joomla-extensions/weblinks/pull/103 once that gets merge you can update your PR.

**Comment by therunnergit** [comment]
@Test still working fine

**Comment by javigomez** [comment]
Please do not merge. I'm sending a pull request to update this pull

**Comment by javigomez** [comment]
tested. works.

I will send an Update with this https://github.com/joomla-extensions/weblinks/issues/128

**Pull request merged**
