### PR TITLE
add php 7.1 and hhvm

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue add php 7.1 and hhvm to tests.

#### Summary of Changes
add php 7.1 and hhvm

#### Testing Instructions
tests are allowed to fail, merge by code review (i.e. test actually run)

### CODE REVIEW

**Comment by zero-24** [comment]
hmm i would not allow 7.0 and 7.1 to fail.

THe PHP CS Checks fails on other problems but 7.0 and 7.1 run fine.

**Comment by photodude** [comment]
@zero-24 the allowed fail change has been implimented

**Comment by zero-24** [comment]
:+1:

**Comment by yvesh** [comment]
@photodude Thank you

**Comment by photodude** [comment]
You are welcome @yvesh

**Pull request merged**
