### PR TITLE
Running phpcs check with travis on php 5.6

### PR DESCRIPTION
**Pull request by yvesh**
#### Summary of Changes

Adding phpcs checks (with joomla rules) to .travis.yml.

As in Joomla! core phpcs is only run with PHP 5.6. They run after the system tests and.

#### Testing Instructions

Look at the result of the travis log for PHP 5.6

screenshot 2016-06-27 21 59 03

### CODE REVIEW

**Comment by zero-24** [comment]
Looks good. I can have a look into the cs issues later this week. If not someone is faster than me ;)

**Comment by zero-24** [comment]
So the most of the issues should be fixed with the last few PRs:
https://github.com/joomla-extensions/weblinks/pull/229
https://github.com/joomla-extensions/weblinks/pull/230
https://github.com/joomla-extensions/weblinks/pull/231
https://github.com/joomla-extensions/weblinks/pull/232
https://github.com/joomla-extensions/weblinks/pull/233
https://github.com/joomla-extensions/weblinks/pull/234

if we get them merged i can have a seccond look over the travis CS issues.

**Comment by yvesh** [comment]
@zero-24 Looks like all your PRs got merged. Can you maybe check if there are more issues and fix them then? :-)

**Comment by zero-24** [comment]
PR is : https://github.com/joomla-extensions/weblinks/pull/251

**Comment by zero-24** [comment]
Can you sync this again with my last PR included?

**Comment by yvesh** [comment]
@zero-24 you commented ten seconds before i did my git push :) Let's see what travis says

**Comment by zero-24** [comment]
Hehe :)

**Comment by yvesh** [comment]
@zero-24 Only one (!!!) left :-)

**Comment by zero-24** [comment]
Hmm i'm sure this should be fixed. I can have a look on it tomorrow :)

**Comment by zero-24** [comment]
Btw. it is just the last travis mention :P the xml files are bad too ;)

**Comment by zero-24** [comment]
@yvesh https://github.com/joomla-extensions/weblinks/pull/254

**Comment by yvesh** [comment]
@zero-24 Hey you made it :-) Green!! 

// Please merge @puneet0191 @javigomez @chrisdavenport

**Comment by zero-24** [comment]
:+1:

**Comment by puneet0191** [comment]
@zero-24 and @yvesh Great work guys, I am merging this one

**Pull request merged**
