### PR TITLE
Implement the JED update.xml

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

- The extension page is still outdated since 3.4.1 released (23 Jul 2015)
- Lets use the new feature (to be tryed) so we can do this per remote

Based on: http://extensions.joomla.org/support/knowledgebase/item/the-update-xml-file
Extension page: http://extensions.joomla.org/extensions/extension/official-extensions/weblinks

#### Testing Instructions

- Apply this patch (or merge)
- go to the extensionlisting and add the update.xml URL

### CODE REVIEW

**Comment by zero-24** [comment]
I'm not sure how has access to the account. Maybe the JED Team can help here?

**Comment by zero-24** [comment]
If someone is logged in that account we can change the listing to be include a component (C) Module (M) and Plugin (P) ;)

**Comment by yvesh** [comment]
@mbabker ping, did you find the credentials for JED? Last time it was lost..

**Comment by mbabker** [comment]
Someone contact the JED to reset it.  The password in the vault isn't right
and the email on the account is most likely turned off so we can't reset it
normally.

**Comment by zero-24** [comment]
@jeckodevelopment can you help with the JED account?

**Comment by mbabker** [comment]
And make sure someone updates the password vault.  It's useless when it has
bad passwords in it.

**Comment by jeckodevelopment** [comment]
@zero-24 and @mbabker of course i can help with the account on the JED.
Who should receive the new password? And, where can i access the Vault?

**Comment by zero-24** [comment]
@jeckodevelopment IIRC the current Weblinkslead is @chrisdavenport but I'm not sure if that is the last information ;)

**Comment by jeckodevelopment** [comment]
So I can provide details to Chris

**Comment by jeckodevelopment** [comment]
I changed the email in the account details.
@chrisdavenport you should be able to change the password using the reset password feature on the JED website.

**Comment by zero-24** [comment]
Thanks :+1: @jeckodevelopment

**Comment by chrisdavenport** [comment]
I have access to the JED account, so I'll merge this then give it a go.

**Comment by zero-24** [comment]
Thanks :+1: Lets hope it works :smile:

**Comment by chrisdavenport** [comment]
JED account updated.  Fingers crossed. :p

**Comment by jeckodevelopment** [comment]
@chrisdavenport if you need help, please ping me.

**Comment by chrisdavenport** [comment]
Thanks @jeckodevelopment.  I assume we now just wait for the cron job to run to see if the listing is updated from the XML?

**Comment by jeckodevelopment** [comment]
yes, but better ask @JazParkyn for this

**Comment by JazParkyn** [comment]
The Update XML cronjob is not functioning as it has a number of bugs that need to be fixed. JED is aiming to look at this after we have sorted the issues with the link checking cron.

**Comment by zero-24** [comment]
Ah Thanks for the update @JazParkyn maybe you can add a quick note to the page i have linked above?

**Comment by JazParkyn** [comment]
Do you mean this page? https://extensions.joomla.org/support/knowledgebase/item/the-update-xml-file

"Note this article is in-work and may change. The XML update feature is not live yet."

**Pull request merged**
