### PR TITLE
Forcing 127.0.0.1 for /etc/hosts in travis

### PR DESCRIPTION
**Pull request by yvesh**
#### Summary of Changes

Fixes Travis tests in weblinks.

#### Testing Instructions

Review travis log

@puneet0191 @rdeutz please merge ASAP so travis starts working again.

### CODE REVIEW

**Comment by puneet0191** [comment]
Thanks @yvesh Looks good. Passes on Travis. Merging.

**Comment by rdeutz** [comment]
@puneet0191 you're fast.

Tried it and it still fails: https://travis-ci.org/rdeutz/weblinks/builds/152374721

**Comment by puneet0191** [comment]
@rdeutz it is a false positive, not related to the PR. Can you try to restart the job of PHP 5.5? It should pass.

**Comment by rdeutz** [comment]
restarting is what I am always doing when just one PHP Version is failing, I did it again and ups it is still failing

**Comment by puneet0191** [comment]
mmh...Something to be fixed in the test, Let me create a new issue so that we review the test and avoid the failure for System Message. Thanks

**Comment by yvesh** [comment]
@rdeutz Hmm the one from the PR and these from my repo are green:

https://travis-ci.org/joomla-extensions/weblinks/builds/152369889

The system tests in weblinks sometimes have hiccups. We are working on improving that :-)

**Comment by rdeutz** [comment]
You said test and I am just reporting my findings :-)

**Comment by yvesh** [comment]
@rdeutz Hehe, i didn't want to say that we will ignore your findings :) Puneet opened an issue and i am going to look into it in the next days.

**Pull request merged**
