### PR TITLE
Using @link over @see

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

using @link over @see

### Testing Instructions

Review

### CODE REVIEW

**Comment by astridx** [comment]
Why do you want to change this annotation? For what do we use the annotations?

I had a look to the description on phpDocumentor https://www.phpdoc.org:

> The @see tag indicates a reference from the associated Structural Elements to a website or other Structural Elements.


And

> The @link tag indicates a custom relation between associated Structural Elements and a website, which is identified by an absolute URI.

I am not sure, but I think "reference" fits better than "custom relation". 

Apart of that: If we want to use phpDocumentor - should we add a description to the annotation?

**Comment by zero-24** [comment]
websites should use the @link tag 😄 @see is for something like a class or object to be checked

Example:

`@see JControllerLegacy`

and

`@link https://joomla.org`

Example warnings i got if we don't do it this way:

image

**Comment by alikon** [comment]
thanks for explanation, the same apply here
https://github.com/joomla/joomla-cms/pull/15302

**Comment by yvesh** [comment]
Thank you @zero-24

**Comment by zero-24** [comment]
Thanks !

**Pull request merged**
