### PR TITLE
Integrated robo build system - clean merge of #125

### PR DESCRIPTION
**Pull request by yvesh**
Clean merge of #125 

### Request for Comments!

This PR is going to integrate a new improved building and packing system based on Robo.li (probably going to be moved to joomla-projects). Making maintenance much easier and testing on live packages possible.

### Instructions to run:

```bash
composer install / update
robo build
```

If you want copy jbuild.dist.ini to jbuild.ini and fit the parameters to your need.

It is going to output a ready to use package file into the dist/ folder. The XML files are now dynamically generated, including file lists, versions, dates and many other things.

In order to achieve that the directory structure is changed to the common Joomla directory structure. The main goal on this is having files symlinkable into joomla installations - making development much easier.

### CODE REVIEW

**Comment by puneet0191** [comment]
Checking the issue with Travis now!

**Comment by zero-24** [comment]
@yvesh we have merge conflicts  here :smiley:

**Comment by yvesh** [comment]
@zero-24 We noticed this too Tobias ;) Going to clean that up and make a new pull request.

**Comment by Kubik-Rubik** [comment]
As discussed at the Code Sprint, I've merged this PR. Thanks for your contribution @yvesh and @nn-medienagentur!

**Pull request merged**
