### PR TITLE
Add sleep time to allow fluxbox and Xvfb launch on Drone.io

### PR DESCRIPTION
**Pull request by javigomez**
# do not merge, this is a test for Continuous integration service.

#### Summary of Changes
This pull is a test to see if the errors at drone.io log are not longer showing up. See https://github.com/joomla-extensions/weblinks/pull/260#discussion_r76099344

#### Testing Instructions
Open droneio log and see if errors have dissapeared

### CODE REVIEW

**Comment by yvesh** [comment]
Hmm no, we can pipe the output of fluxbox to /dev/null like we do with xvfb, can you update that fluxbox line @javigomez to:

```bash
fluxbox  > /dev/null 2>&1 &
```

Then you can set the wait time back to three (makes execution faster).

**Comment by javigomez** [comment]
ah, right, let me fix.

**Comment by yvesh** [comment]
Looks good - thank you @javigomez

**Comment by javigomez** [comment]
Thanks.

For reference I'm leaving here the 'before log': http://82.165.166.30/joomla-extensions/weblinks/8
and the 'after log': http://82.165.166.30/joomla-extensions/weblinks/9

**Pull request merged**
