### PR TITLE
Fix for failing code style tests

### PR DESCRIPTION
**Pull request by chrisdavenport**
Pull Request for Issue #282 .

#### Summary of Changes
PHP and JS headers were changed during the 3.6.0-beta release procedure.  This PR fixes the source of that problem.

#### Testing Instructions
Run `vendor/bin/robo headers` and check that headers in PHP and JS files are correct.

### CODE REVIEW

**Comment by zero-24** [comment]
I guess you missed to run the script? Btw if you add the subpackage tag again we dont need to change the spaces ;)

**Comment by chrisdavenport** [comment]
Is that better?

**Comment by zero-24** [comment]
CS is done now. The 5.6 fail is now something different (something about a screenshot) maybe @yves can help there?

**Comment by yvesh** [comment]
@zero-24 It's the usual Travis hickup, rest looks fine.

**Comment by yvesh** [comment]
Thanks @chrisdavenport :+1:

**Pull request merged**
