### PR TITLE
Enable cache for vendor folder

### PR DESCRIPTION
**Pull request by yvesh**
Pull Request for Issue #264 

#### Summary of Changes

Add vendor folder to drone.io cache

#### Testing Instructions

Check drone.io log and if it passes merge, so we can test if time is improved.

### CODE REVIEW

**Comment by zero-24** [comment]
Travis is happy / green :smile:

**Comment by javigomez** [comment]
@yvesh I was checking documentation and I saw that there is no automatic way to flush the cache: http://readme.drone.io/usage/caching/#deleting-the-cache:ac010da762d8cf87ef4765b457c06928.

What is the plan for when we update the composer packages?

**Comment by javigomez** [comment]
Also I'm not sure that cache is working. Maybe it will not work until this pull is merged.

To proof it try to reestart the current build http://82.165.166.30/joomla-extensions/weblinks/12 and then reestart a earlier build before "caching" was active, for example http://82.165.166.30/joomla-extensions/weblinks/11. You will notice that the time taken for downloading a package is the same.

**Comment by yvesh** [comment]
@javigomez we don't need to flush the cache, composer install does that for us.

I am not sure when the cache starts working. Probably first when we merged this PR - currently it's always redownloading the packages (else it would state -> Install from cache)

**Comment by yvesh** [comment]
Okay looked at it again, we need to change the build script in order for caching to work.. Updating that PR in some minutes

**Comment by yvesh** [comment]
Can somebody please merge that? The caching starts after this is in the master branch.. Tested that on my personal repository.

**Pull request merged**
