### PR TITLE
Move lang files for search plugin

### PR DESCRIPTION
**Pull request by chrisdavenport**
#### Summary of Changes
Move language files for the search plugin into the plugin distribution file.  This makes all the plugins consistent in not putting language files into administrator/language.

#### Testing Instructions
Upgrade an existing web links installation and make sure there are no web links language files in administrator/language/en-GB.  Make sure language strings for the search plugin are still working.

### CODE REVIEW

**Comment by astridx** [comment]
I tested this successful.

1. I applied your patch
2. I deleted the files en-GB.plg_search_weblinks.ini and en-GB.plg_search_weblinks.sys.ini in the language admin folder. They have been already there in my case. 
3. I make sure, that the language files are already working.


I only would suggest to start the name of the class with a upper case letter.


bildschirmfoto vom 2017-01-08 11-22-50

**Comment by zero-24** [comment]
@chrisdavenport i have send you a PR: https://github.com/chrisdavenport/weblinks/pull/1 that reduces the code and use the Joomla API to do that stuff.

**Comment by chrisdavenport** [comment]
Thanks @zero-24

**Comment by yvesh** [comment]
This needs fixing a bug in the build script JoRobo first. (It ignores language files in the plugin folder currently)

**Comment by zero-24** [comment]
@chrisdavenport please fix the merge conflicts and or allow the maintainer edits. Thanks 😄

**Comment by zero-24** [comment]
> This needs fixing a bug in the build script JoRobo first. (It ignores language files in the plugin folder currently)

I expect this is done already?

**Comment by zero-24** [comment]
Closing here because there is no update. I have done a new PR with the needed changes #334

**Pull request closed without merging**
