### PR TITLE
Add category items count

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
This PR adds count of item sin weblinks category like it was done for the other core components.

image

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I submited this PR
I waited for travis checks
I don't have a clue why the test failed
I ask for some help here

:wink:

**Comment by yvesh** [comment]
@andrepereiradasilva Travis checks are currently broken, because of an issue with creating menu items in joomla-browser v3.4.8.2. It already has been fixed and we made a new release. After merging #205 checks should work again.

**Comment by andrepereiradasilva** [comment]
ok thanks. So the PR it's fine.

I ask for testers. ;)

**Comment by andrepereiradasilva** [comment]
BTW the links in the numbers don't work yet.
Will work after a new PR i'm preparing.

**Comment by andrepereiradasilva** [comment]
supperseed by https://github.com/joomla-extensions/weblinks/pull/208

**Pull request closed without merging**
