### PR TITLE
Language files

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/16753

### Summary of Changes
Moves the language files from the global language folder to the component/module specific.
During install and update, the en-GB files in the global folder are deleted.

### Testing Instructions
Install the component and make sure the language files in the global language folders are deleted. Test that the strings in Weblinks still are coming in english and not the "untranslated" strings (eg not COM_WEBLINKS_FOO)

### Expected result
Language files served from the extension and not from core

### Actual result
Language files are served by core

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Bakual** [comment]
It has yet to be decided how the translations itself (eg german) should be handled.
The crowdin.yml file present in this PR would be the integration into Crowdin. https://crowdin.com/project/joomla-weblinks-extension is set up so it fetchs the files from this branch on my repo and write back the translations to a new branch https://github.com/bakual/weblinks/tree/l10n_LanguageFiles. It also creates a PR automatically (see https://github.com/Bakual/weblinks/pull/2).

I left it in so you can see it. It obviously has to be changed to work from this repo instead if accepted.
Also the exported translation files can't be automatically renamed to "de-DE.com_weblinks.ini". That needs a solution as well.

**Comment by infograf768** [comment]
what about the specific plugins language files ? (looked from ipad, correct me if I am wrong)

**Comment by Bakual** [comment]
From what I saw, they already have the source files in the component specific folders within this repo.
Only the component, module and package ones where in the global one.
I moved the component and module one. For the package I think that needs to stay in the global as I don't know where to place that otherwise. My own extension package doesn't have a language file :smile: 

I'm not sure in which code the module and plugin files should be deleted from the global folder. The right and more failsafe thing would probably be to add a script file to each of them and do it there.
The more pragmatic way is to just do it in the component script for the modules and plugins as well.

**Comment by mbabker** [comment]
> For the package I think that needs to stay in the global as I don't know where to place that otherwise.

Files and packages extensions have to use the global folder, there really isn't another place to put them.

**Comment by astridx** [comment]
> From what I saw, they already have the source files in the component specific folders within this repo.
> Only the component, module and package ones where in the global one.
> 

In the Manifest XML of all plugins the language is configured as

```
	<languages folder="administrator/language">
		##LANGUAGE_FILES##
	</languages>

```

AFAIK the text `##LANGUAGE_FILES##` is changed in the build-process. On the position of `##LANGUAGE_FILES##` the build process insert the files that are saved in the directory WORKDIRECTORY/weblinks/src/language. The build process only insert something if there are language files with a name that fits with the name of the extension.

As there are no language files for the plugins in the directory WORKDIRECTORY/weblinks/src/language, the is no file inserted in the Manifest XML.

I asked this in the past and I get the answer, that web links do not need to offer files, because the files are in Joomla! core.

So I think we have to edit the Manifest XML ot the plugin, too.

**Comment by Bakual** [comment]
Ah didn't notice this. I just looked at the repo. Then those manifests need to be changed as well. I'll update the PR this evening.

**Comment by Bakual** [comment]
I have removed the tags from the manifests. It should be fine now.

**Comment by franz-wohlkoenig** [comment]
@Bakual can [#16753](https://github.com/joomla/joomla-cms/issues/16753) be closed?

**Comment by Bakual** [comment]
@franz-wohlkoenig I would leave it open for now. To many PRs which all have to be merged to get it working this way.
I'm not even sure if all aspects already are taken care of.

**Comment by Bakual** [comment]
I'm closing this as everything related to Crowdin is goign to change anyway. So this PR doesn't make any sense anymore.

**Pull request closed without merging**
