### PR TITLE
Convert remaining "Weblinks" text to "Web Links"

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
This PR converts remaining "Weblinks" text to "Web Links" as most of then already are.

Simple test by code review.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
humm ... should the tests be based on language variables?

**Comment by puneet0191** [comment]
@andrepereiradasilva we do it for readability, I understand your point, but for us it saves time, some places we have to do it to solve the purpose of the test. :smile:

**Comment by yvesh** [comment]
@andrepereiradasilva Some are, as it makes the tests easier and more readable. The downside of that you just encountered.. But you have the same when you use CSS / Xpath locators and change styles (h3 -> h2) etc.

**Comment by andrepereiradasilva** [comment]
Yes, i understand. Is no easy choice.

Anyway, it's solved now.

**Comment by puneet0191** [comment]
@andrepereiradasilva  thank you :+1:

**Comment by yvesh** [comment]
@andrepereiradasilva Looks fine too me, based on code review. Thank you 👍

**Comment by andrepereiradasilva** [comment]
you're welcome guys.

thanks you all for your work in the browser tests!
And always be available to give help when needed!

**Comment by pritalpatel** [comment]
Thank you for PR. When I was trying to test it using codeception found that space is missing in category and that is why test was failing.
weblink-auto-space-errror


Please add space here in category view. 
no-space-weblinks

**Comment by andrepereiradasilva** [comment]
@pritalpatel there are no tests failing. i think that was already solved.

**Comment by pritalpatel** [comment]
sorry @andrepereiradasilva I was trying to test again this PR. All assertion run smoothly and looks fine.
210weblinks
Thank you.

**Comment by infograf768** [comment]
The lang strings changes should also be done in the core folders.

Also, should this string (in com_weblinks.sys.ini) be modified from
` COM_WEBLINKS_CATEGORIES_VIEW_DEFAULT_DESC="Show all the web link categories within a category."`
to
` COM_WEBLINKS_CATEGORIES_VIEW_DEFAULT_DESC="Show all the Web Links categories within a category."`
on the model of the module:
`MOD_WEBLINKS_FIELD_CATEGORY_DESC="Choose the Web Links category to display."`

Other discrepancy (typo, lowercase) in the module ini:
`MOD_WEBLINKS_XML_DESCRIPTION="This modules displays web links from a category defined in the Web Links component."`
and the module sys.ini (typo):
`MOD_WEBLINKS_XML_DESCRIPTION="This modules displays Web Links from a category defined in the Web Links component."`

**Pull request merged**
