### PR TITLE
Add PHP7 Check Travis

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by 810** [comment]
Php check is working, only there is a issue on the test part with php7.

**Comment by jatitoam** [comment]
It seems we're working on the same :) https://github.com/joomla-extensions/weblinks/pull/248
and having the same problem

**Comment by 810** [comment]
@jatitoam yes i copied your code, but then only php7 works, so I added a check for both versions:

You can see here that the code is correct: https://github.com/Kunena/Kunena-Forum/pull/4198

**Comment by jatitoam** [comment]
Yeah, definitely, I was working on the PHP7-compatibility issue before getting there
Thanks for that

**Comment by jatitoam** [comment]
I sent https://github.com/joomla-extensions/weblinks/pull/250 to improve this PR

**Comment by yvesh** [comment]
@810 Jelle, looks like everything is working now. Can you do a final check before we merge it into master branch? :-)

**Pull request merged**
