### PR TITLE
Make tool bar filter fields nice and multiple

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes
The filter fields in the tool bar are multiple now.

### Testing Instructions
Open the web links component in the back end. The filter fields are looking like in the next picture.
web links test administration

Apply the patch and open the web links component in the back end again. Now the filter fields are multiple and look like in the next picture.
web links test administration 1

Please also test if the fields are still working properly by testing different selection combinations

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 6687454865d489cb473e4b71f9ece254ca2413c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/377">issues.joomla.org/tracker/weblinks/377</a>.</sub>

**Comment by yvesh** [comment]
@astridx can you check the notices? Thanks :-)

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you very much for testing :)

and sorry, I must have forgotten to activate the error reporting. Otherwise I have no explanation for not seeing this :)
But now this should be fixes.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 6aa57c0057c747d5951aa4b5bcf29ebf6c6c1ae2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/377">issues.joomla.org/tracker/weblinks/377</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 6aa57c0057c747d5951aa4b5bcf29ebf6c6c1ae2<br /><br />Installing PR got:

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/377">issues.joomla.org/tracker/weblinks/377</a>.</sub>

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you for testing. Can you tell me when exactly this message appeared?

**Comment by franz-wohlkoenig** [comment]
Message come up after calling `administrator/index.php?option=com_weblinks`

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you for testing. I just made some tests and I do not see a sql error.
There have been much changes since May. So I have just created an installable web links file of my current branch. 
It would be much more meaningful if someone else would create this. As I do not expect that, I put the file here once.
@franz-wohlkoenig 
If you like, you can install web links with this file and redo the test. [pkg-weblinks-current.zip](https://github.com/joomla-extensions/weblinks/files/1451467/pkg-weblinks-current.zip)

**Comment by franz-wohlkoenig** [comment]
thanks @astridx This zip is for Test of all PRs?

**Comment by franz-wohlkoenig** [comment]
Installation works, but Warning: `JInstaller: :Install: File does not exist /Applications/MAMP/htdocs/3/tmp/install_5a02a1cea37f6/install_5a02a1ceabfd7/media/js`
bildschirmfoto 2017-11-08 um 07 20 24

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6aa57c0057c747d5951aa4b5bcf29ebf6c6c1ae2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/377">issues.joomla.org/tracker/weblinks/377</a>.</sub>

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you very much for testing.

`This zip is for Test of all PRs?` For your information: The uploaded zip is the version form 02. November after merging https://github.com/joomla-extensions/weblinks/pull/317 and https://github.com/joomla-extensions/weblinks/pull/349

But I forgot this https://github.com/joomla-extensions/weblinks/pull/372 - that is why you saw the error while installing

**Comment by franz-wohlkoenig** [comment]
thanks for Info @astridx. Can willing Testers get nightly Builds similar to CMS or an easy Way to test with up-to-date-Buildings?

**Comment by astridx** [comment]
@franz-wohlkoenig  AFAIK there is no nightly Build for web links.

@All I think it is on the time to create a new release. I never did this before. I see the button Draft a new release, so I think I have the rights for doing this. Should I do this?

**Comment by infograf768** [comment]
Folks, I think we should first release a beta as an installable .zip to test things.

**Comment by infograf768** [comment]
Then, we have to add the correct ini strings to J core

**Pull request closed without merging**
