### PR TITLE
Xmlcs

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # .

### Summary of Changes
Add some tabs and deleted some empty lines. Only coding standard changes

### CODE REVIEW

**Comment by yvesh** [comment]
Thank you @zero-24 and @astridx

**Comment by astridx** [comment]
I accidentally created a new PR

**Comment by yvesh** [comment]
No issue, it contained Tobias as author

**Comment by astridx** [comment]
Thank you Yves. Although I made a mistake.  I want to ask @zero-24 if he merge my additions. But I will certainly have more opportunity to test PRs :)

**Pull request merged**
